# Generated by Django 4.2.7 on 2026-04-21 10:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="files/avatars/"
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_location", models.CharField(blank=True, max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("applicant", "Applicant"),
                        ],
                        default="applicant",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="files/resumes/"),
                ),
                ("resume_text", models.TextField(blank=True)),
                ("resume_generated", models.BooleanField(default=False)),
                ("ai_analysis_result", models.JSONField(default=dict)),
                ("compatibility_score", models.IntegerField(default=0)),
                ("ai_strengths", models.JSONField(default=list)),
                ("ai_weaknesses", models.JSONField(default=list)),
                ("ai_recommendations", models.JSONField(default=list)),
                ("interview_analysis", models.JSONField(default=dict)),
                ("interview_score", models.IntegerField(default=0)),
                (
                    "user_language",
                    models.CharField(
                        choices=[("uz", "O'zbek"), ("ru", "Русский")],
                        default="uz",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("ai_analyzing", "AI tahlil qilinmoqda"),
                            ("rejected_resume", "Resume rad qilindi"),
                            ("interview_stage", "Suhbat bosqichida"),
                            ("rejected_interview", "Suhbat rad qilindi"),
                            ("accepted", "Qabul qilindi"),
                            ("hired", "Ishga qabul qilindi"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("final_score", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.JSONField(default=dict)),
                ("description", models.JSONField(default=dict)),
                ("requirements", models.JSONField(default=dict)),
                ("responsibilities", models.JSONField(default=dict)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("remote", "Masofaviy"),
                            ("office", "Ofisda"),
                            ("hybrid", "Aralash"),
                        ],
                        default="office",
                        max_length=20,
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        choices=[
                            ("full-time", "To'liq kunlik"),
                            ("part-time", "Yarim kunlik"),
                            ("contract", "Shartnoma"),
                        ],
                        default="full-time",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("experience_years", models.IntegerField(default=0)),
                ("experience_months", models.IntegerField(default=0)),
                ("ai_criteria", models.JSONField(blank=True, default=dict, null=True)),
                ("ai_prompt", models.TextField(blank=True, null=True)),
                ("min_match_score", models.IntegerField(default=70)),
                (
                    "unique_link",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Faol"), ("archived", "Arxivlangan")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("applications_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("portfolio_url", models.URLField(blank=True, null=True)),
                ("education_data", models.JSONField(default=list)),
                ("experience_data", models.JSONField(default=list)),
                ("technical_skills", models.JSONField(default=list)),
                ("soft_skills", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("projects_data", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("hobbies", models.TextField(blank=True)),
                ("references", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_form_data",
                        to="api.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=50,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("completed", "Yakunlandi"),
                            ("terminated", "To'xtatildi"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("questions_asked", models.IntegerField(default=0)),
                ("termination_reason", models.CharField(blank=True, max_length=255)),
                ("final_score", models.IntegerField(default=0)),
                ("final_analysis", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_session",
                        to="api.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="api.vacancy",
            ),
        ),
        migrations.CreateModel(
            name="ApplicantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                (
                    "demo_username",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                ("demo_password_hash", models.CharField(blank=True, max_length=128)),
                ("session_token", models.CharField(blank=True, max_length=64)),
                ("last_issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicant_profiles",
                        to="api.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("vacancy", "phone")},
        ),
    ]
