# Generated by Django 4.2.7 on 2026-04-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="credentials_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
