# Generated by Django 4.2.7 on 2026-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_application_credentials_issued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ai_analysis_translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
