# Generated by Django 4.2.7 on 2026-04-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_application_ai_analysis_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="interview_analysis_translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
