# Generated by Django 4.2.7 on 2026-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_application_interview_analysis_translations"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "-applied_at"], name="app_status_applied_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["vacancy", "status"], name="app_vacancy_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["phone"], name="app_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["status", "-created_at"], name="vac_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["employer", "status"], name="vac_employer_status_idx"
            ),
        ),
    ]
