# Generated by Django 4.2.7 on 2026-04-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_application_app_status_applied_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Telegram username (@ bilan yoki belgisiz)",
                max_length=64,
            ),
        ),
    ]
