# Generated by Django 4.2.7 on 2026-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_application_telegram_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="off_topic_strikes",
            field=models.IntegerField(default=0),
        ),
    ]
