# Generated by Django 4.2.7 on 2026-04-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("ai_analyzing", "AI tahlil qilinmoqda"),
                    ("rejected_resume", "Resume rad qilindi"),
                    ("interview_stage", "Suhbat bosqichida"),
                    ("interview_abandoned", "Intervyudan chiqib ketdi"),
                    ("rejected_interview", "Suhbat rad qilindi"),
                    ("talent_pool", "Baza sifatida saqlandi"),
                    ("accepted", "Qabul qilindi"),
                    ("in_contact", "Aloqada"),
                    ("hired", "Ishga qabul qilindi"),
                    ("admin_cancelled", "Admin tomonidan bekor qilindi"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
