# Generated by Django 4.2.7 on 2026-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeformdata",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
