# Generated by Django 4.2.7 on 2026-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_resumeformdata_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
