# Generated by Django 4.2.7 on 2026-04-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_user_telegram_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
