# Generated by Django 4.2.7 on 2026-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_application_status_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="demo_credentials",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="application",
            name="poll_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
